# development environment
FROM registry.cn-shenzhen.aliyuncs.com/yding/nginx:alpine
ADD ./dist /usr/src/app/dist
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]