version: "3"

services:
  website-web:
    restart: always
    image: nginx:alpine
    container_name: website-web
    volumes:
      - ./dist:/usr/src/app/dist
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8018:80
